version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg15
    container_name: location-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: location_db
    volumes:
      - location-db-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d  # 초기화 스크립트 자동 실행
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d location_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  location-db-data:
    name: location-db-data
